[0m15:08:44.567207 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f3dde50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111723310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111797760>]}


============================== 15:08:44.571718 | aae359e3-9dae-4218-a245-e590ad8fe5c8 ==============================
[0m15:08:44.571718 [info ] [MainThread]: Running with dbt=1.7.2
[0m15:08:44.572474 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/toniamayaobrador/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:08:44.573379 [info ] [MainThread]: dbt version: 1.7.2
[0m15:08:44.573864 [info ] [MainThread]: python version: 3.9.21
[0m15:08:44.574331 [info ] [MainThread]: python path: /Users/toniamayaobrador/miniconda3/envs/dbt39_env/bin/python3.9
[0m15:08:44.574793 [info ] [MainThread]: os info: macOS-10.16-x86_64-i386-64bit
[0m15:08:45.084976 [info ] [MainThread]: Using profiles dir at /Users/toniamayaobrador/.dbt
[0m15:08:45.085820 [info ] [MainThread]: Using profiles.yml file at /Users/toniamayaobrador/.dbt/profiles.yml
[0m15:08:45.086365 [info ] [MainThread]: Using dbt_project.yml file at /Users/toniamayaobrador/dbt_weather/weather/dbt_project.yml
[0m15:08:45.086869 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m15:08:45.089217 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.6204973, "process_user_time": 2.909447, "process_kernel_time": 0.234829, "process_mem_max_rss": "122888192", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:08:45.089896 [debug] [MainThread]: Command `dbt debug` failed at 15:08:45.089671 after 0.62 seconds
[0m15:08:45.090459 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f3dde50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1122ff130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1122ffac0>]}
[0m15:08:45.090894 [debug] [MainThread]: Flushing usage events
