[0m15:08:44.567207 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f3dde50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111723310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111797760>]}


============================== 15:08:44.571718 | aae359e3-9dae-4218-a245-e590ad8fe5c8 ==============================
[0m15:08:44.571718 [info ] [MainThread]: Running with dbt=1.7.2
[0m15:08:44.572474 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/toniamayaobrador/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:08:44.573379 [info ] [MainThread]: dbt version: 1.7.2
[0m15:08:44.573864 [info ] [MainThread]: python version: 3.9.21
[0m15:08:44.574331 [info ] [MainThread]: python path: /Users/toniamayaobrador/miniconda3/envs/dbt39_env/bin/python3.9
[0m15:08:44.574793 [info ] [MainThread]: os info: macOS-10.16-x86_64-i386-64bit
[0m15:08:45.084976 [info ] [MainThread]: Using profiles dir at /Users/toniamayaobrador/.dbt
[0m15:08:45.085820 [info ] [MainThread]: Using profiles.yml file at /Users/toniamayaobrador/.dbt/profiles.yml
[0m15:08:45.086365 [info ] [MainThread]: Using dbt_project.yml file at /Users/toniamayaobrador/dbt_weather/weather/dbt_project.yml
[0m15:08:45.086869 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m15:08:45.089217 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.6204973, "process_user_time": 2.909447, "process_kernel_time": 0.234829, "process_mem_max_rss": "122888192", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:08:45.089896 [debug] [MainThread]: Command `dbt debug` failed at 15:08:45.089671 after 0.62 seconds
[0m15:08:45.090459 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f3dde50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1122ff130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1122ffac0>]}
[0m15:08:45.090894 [debug] [MainThread]: Flushing usage events
[0m01:16:09.396380 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106ad9eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e21640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e66280>]}


============================== 01:16:09.403280 | ede2f259-c58b-417a-908a-a3ce47ed3b00 ==============================
[0m01:16:09.403280 [info ] [MainThread]: Running with dbt=1.7.2
[0m01:16:09.404243 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/toniamayaobrador/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt compile', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m01:16:09.405183 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/toniamayaobrador/dbt_weather_dagster/weather/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:16:09.408758 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.13753739, "process_user_time": 3.233437, "process_kernel_time": 0.242013, "process_mem_max_rss": "103108608", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m01:16:09.409437 [debug] [MainThread]: Command `dbt compile` failed at 01:16:09.409261 after 0.14 seconds
[0m01:16:09.410075 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106ad9eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e66160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e66f40>]}
[0m01:16:09.410753 [debug] [MainThread]: Flushing usage events
[0m12:25:47.561598 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10dfb8fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110324340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110358460>]}


============================== 12:25:47.567113 | 66928ce8-394c-4d03-9d0a-1c0f203a70f7 ==============================
[0m12:25:47.567113 [info ] [MainThread]: Running with dbt=1.7.2
[0m12:25:47.567889 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/toniamayaobrador/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt compile', 'send_anonymous_usage_stats': 'True'}
[0m12:25:47.568720 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/toniamayaobrador/dbt_weather_dagster/weather/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:25:47.572542 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.11590478, "process_user_time": 2.715275, "process_kernel_time": 0.2726, "process_mem_max_rss": "103706624", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m12:25:47.573294 [debug] [MainThread]: Command `dbt compile` failed at 12:25:47.573055 after 0.12 seconds
[0m12:25:47.573867 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10dfb8fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110358a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110358460>]}
[0m12:25:47.574450 [debug] [MainThread]: Flushing usage events
[0m19:45:12.290192 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e39220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10718c3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071df5b0>]}


============================== 19:45:12.295184 | 52c70df6-a9c6-410d-9b57-cea599b2f8ad ==============================
[0m19:45:12.295184 [info ] [MainThread]: Running with dbt=1.7.2
[0m19:45:12.296053 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/toniamayaobrador/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt build --select weather_current_metrics', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:45:12.296868 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/toniamayaobrador/dbt_weather_dagster/weather/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:45:12.299873 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.12782416, "process_user_time": 2.653547, "process_kernel_time": 0.186534, "process_mem_max_rss": "103972864", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:45:12.300549 [debug] [MainThread]: Command `dbt build` failed at 19:45:12.300344 after 0.13 seconds
[0m19:45:12.301108 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e39220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10718c3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071df5b0>]}
[0m19:45:12.301663 [debug] [MainThread]: Flushing usage events
